apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-component
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=my-app"
spec:
  type: service
  lifecycle: experimental
  owner: default-owner
