apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-workload
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: my-app
spec:
  source:
    git:
      url: https://example.com/
      ref:
        branch: main
